---
name: Run markdownlint-cli2 and set annotations
description: Run markdownlint-cli2 and set annotations.

inputs:
  ### Flags for prettier ###
  markdownlint_version:
    description: "The version of markdownlint-cli2 to install"
    default: "latest"
    required: false
  markdownlint_config:
    description: "Config file to pass to the markdownlint-cli2 command"
    required: false
    default: ""
  file_pattern:
    description: "Files to lint"
    required: false
    default: "**/*.md"

runs:
  using: "composite"

  steps:
    - name: Register problem matcher
      shell: bash
      run: |
        cp "$GITHUB_ACTION_PATH/src/matcher.json" "markdownlint-cli2-matcher.json"
        echo "::add-matcher::markdownlint-cli2-matcher.json"

    - name: Run markdownlint-cli2
      run: $GITHUB_ACTION_PATH/src/script.sh
      shell: bash
      env:
        MARKDOWNLINT_VERSION: ${{ inputs.markdownlint_version }}
        MARKDOWNLINT_CONFIG_FILE: ${{ inputs.markdownlint_config }}
        FILE_PATTERN: ${{ inputs.file_pattern }}
